### ISSUE TITLE
迁移并不会删除package.json里面的eslintConfig吗

### ISSUE THREAD

**Issue by zhanyi233** [cool-fe/winex-cli#35] opened 2021-05-26 02:28 UTC
![image](https://user-images.githubusercontent.com/37531008/119593724-0acd2180-be0d-11eb-8667-fb878ed311de.png)

**Comment by GGwujun** [comment] 2021-05-26 05:39
Duplicate of #26

**Closed** 2021-05-26 05:40 UTC
